info:
  description: |
    Please refer [IoT Public API Authentication](iot-public-api-headers) to know how to get API Key<br/>
    List of public APIs from IoT security:
    1. Link to [Get Device Detail](iot-public-api#operation/device-detail)
    2. Link to [Get Device Inventory](iot-public-api#operation/device-inventory)
    3. Link to [Get Security Alerts](iot-public-api#operation/alert-list)
    4. Link to [Resolve a Security Alert](iot-public-api#operation/alert-resolve)
    4. Link to [Get Vulnerabilities](iot-public-api#operation/vulnerability-list)
    4. Link to [Resolve Vulnerability Instances](iot-public-api#operation/vulnerability-resolve)
  title: IoT Public API Overview
  version: v4.0
  contact: {}
openapi: 3.0.0
servers:
- url: https://{customer-name}.iot.paloaltonetworks.com
tags:
- description: The IoT Public APIs are listed below.
  name: IoT Public API
paths:
  /pub/v4.0/device:
    get:
      description: 'Get a list of device details for the device with the specified MAC address. <br/> <b>Rate limiting<b/>: 60 times per minute'
      operationId: device-detail
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Device Detail
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/deviceDetail.yaml#/parameters'
      responses:
        $ref: 'api/public/deviceDetail.yaml#/responses'

  /pub/v4.0/device/list:
    get:
      description: 'Get a list of all the devices in your IoT Security inventory. <br/> <b>Rate limiting<b/>: 60 times per minute'
      operationId: device-inventory
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Device Inventory
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/deviceList.yaml#/parameters'
      responses:
        $ref: 'api/public/deviceList.yaml#/responses'

  /pub/v4.0/alert/list:
    get:
      description: 'Get a list of security alerts. <br/> <b>Rate limiting<b/>: 60 times per minute'
      operationId: alert-list
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Security Alerts
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/alertList.yaml#/parameters'
      responses:
        $ref: 'api/public/alertList.yaml#/responses'

  /pub/v4.0/alert/update:
    put:
      description: 'Resolve a security alert. <br/> <b>Rate limiting<b/>: 60 times per minute'
      operationId: alert-resolve
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Resolve a Security Alert
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/alertResolve.yaml#/parameters'
      requestBody:
        $ref: 'api/public/alertResolve.yaml#/requestBody'
      responses:
        $ref: 'api/public/alertResolve.yaml#/responses'

  /pub/v4.0/vulnerability/list:
    get:
      description: 'Get a list of security alerts. <br/> <b>Rate limiting<b/>: 60 times per minute'
      operationId: vulnerability-list
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Vulnerabilities
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/vulnerabilityList.yaml#/parameters'
      responses:
        $ref: 'api/public/vulnerabilityList.yaml#/responses'

  /pub/v4.0/vulnerability/update:
    put:
      description: 'Mark one or more instances of a vulnerability as resolved. <br/> <b>Rate limiting<b/>: 60 times per minute'
      operationId: vulnerability-resolve
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Resolve Vulnerabilty Instances
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/vulnerabilityResolve.yaml#/parameters'
      requestBody:
        $ref: 'api/public/vulnerabilityResolve.yaml#/requestBody'
      responses:
        $ref: 'api/public/vulnerabilityResolve.yaml#/responses'

  /pub/v4.0/device/bulkUpdate:
    put:
      description: 'General bulk update devices. Currently, it is being used for DNAC and Cisco Prime integrations.'
      operationId: general-bulk-update
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Bulk Update Devices - General
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/bulkUpdate.yaml#/parameters'
      requestBody:
        $ref: 'api/public/bulkUpdate.yaml#/requestBody'
      responses:
        $ref: 'api/public/bulkUpdate.yaml#/responses'

  /pub/v4.0/device/bulkUpdate?updateSource=cisco_wlc:
    put:
      description: 'Bulk update devices for Cisco WLC'
      operationId: cisco-wlc-bulk-update
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Bulk Update Devices - Cisco WLC
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/bulkUpdateCiscoWLC.yaml#/parameters'
      requestBody:
        $ref: 'api/public/bulkUpdateCiscoWLC.yaml#/requestBody'
      responses:
        $ref: 'api/public/bulkUpdateCiscoWLC.yaml#/responses'

  /pub/v4.0/device/bulkUpdate?updateSource=aruba_wlc:
    put:
      description: 'Bulk update devices for Aruba WLC'
      operationId: aruba-wlc-bulk-update
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Bulk Update Devices - Aruba WLC
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/bulkUpdateArubaWLC.yaml#/parameters'
      requestBody:
        $ref: 'api/public/bulkUpdateArubaWLC.yaml#/requestBody'
      responses:
        $ref: 'api/public/bulkUpdateArubaWLC.yaml#/responses'

  /pub/v4.0/device/bulkUpdate?updateSource=snmp:
    put:
      description: 'Bulk update devices for SNMP'
      operationId: snmp-bulk-update
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Bulk Update Devices - SNMP
      tags:
        - IoT Public API
      parameters:
        $ref: 'api/public/bulkUpdateSNMP.yaml#/parameters'
      requestBody:
        $ref: 'api/public/bulkUpdateSNMP.yaml#/requestBody'
      responses:
        $ref: 'api/public/bulkUpdateSNMP.yaml#/responses'

  /pub/v4.0/xsoar/status:
    post:
      description: 'Receiving Xsoar Playbook status. <br/> <b>Default Rate limiting<b/>: 180 times per minute'
      operationId: xsoar-playbook-status
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Xsoar Playbook Status
      tags:
        - IoT Public API
      parameters:
        - description: The customer ID specifies the API call for a specific tenant.
          in: query
          name: customerid
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
                - timestamp
                - integration_name
                - playbook_name
              properties:
                status:
                  type: string
                  description: 'The Xsoar Playbook status. Possible values: [error, success, disabled].'
                timestamp:
                  type: integer
                  description: 'The timestamp when sending the status to cloud side in milliseconds.'
                integration_name:
                  type: string
                  description: 'The third-party integration name of the playbook.'
                playbook_name:
                  type: string
                  description: 'The Xsoar Playbook name.'
                message:
                  type: string
                  description: 'The messages received from Xsoar Playbook.'
                custom_integration_name:
                  type: string
                  description: 'The custom integration name.'
            examples:
              payloadExample:
                summary: An example of payload of sending Xsoar Playbook status
                value:
                  status: error
                  integration_name: servicenow
                  playbook_name: Bulk Export Devices to ServiceNow - PANW IoT 3rd Party Integration
                  message: Failed to do a bulk device sync to ServiceNow. Please see the detailed error message from the playbook
                  timestamp: 1626827123
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  resceived:
                    type: string
                    description: Confirmation from cloud side.
              examples:
                value: {
                  received: 'yes'
                }
        '4XX':
          description: Client Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Bad Request:
                  $ref: '#/components/examples/BadRequestResponseExample'
                Unauthrorized Request:
                  $ref: '#/components/examples/UnauthorizedResponseExample'
          '5XX':
            description: Server Error Response
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
                examples:
                  resolveSecurityAlertResponseExample:
                    $ref: '#/components/examples/ServerErrorResponseExample'

  /pub/v4.0/xsoar/device/scanDetails:
    post:
      description: 'Receiving the scanner list and profile list for the specific scanner.'
      operationId: xsoar-device-scan-detail
      security:
      - X-Key-Id:  []
        X-Access-Key: []
      summary: Receiving Vulnerability Scanner Metadata
      tags:
        - IoT Public API
      parameters:
        - description: The customer ID specifies the API call for a specific tenant.
          in: query
          name: customerid
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - scannerList
                - profileList
                - scanType
                - timestamp
              properties:
                scannerList:
                  type: array
                  description: 'The array of scanners or engines.'
                profileList:
                  type: array
                  description: 'The array of profiles or templates.'
                siteIdList:
                  type: array
                  description: 'The site id list. It is required for Rapid7.'
                scanType:
                  type: string
                  description: 'The type of device vulnerability scan.'
                timestamp:
                  type: integer
                  description: 'The timestamp when sending the metadata to cloud side in milliseconds.'
            examples:
              - payloadExample:
                summary: Payload Example sending Qualys scan details
                value:
                  profileList: ["WannaCry and Shadow Brokers", "2008 SANS20 Options"]
                  scannerList: ["Scanner-1"]
                  scanType: 'qualys'
                  timestamp: 1590881696000
              - payloadExample:
                summary: Payload Example sending Rapid7 scan details
                value:
                  scannerList: [{"engineId": "1", "engineName": "test engine"}]
                  profileList: [{"templateId": "1", "templateName": "test tempalte"}]
                  siteIdList: [{"siteId": "134", "siteName": "zingbox office"}, {"siteId": "2", "siteName": "panw office"}]
                  scanType: 'rapid7'
                  timestamp: 1590881696000
              - payloadExample:
                summary: Payload Example sending Tenable scan details
                value:
                  profileList: [{"profileId": "fc2fa8b3-028b-83e8-2ebd-4705d0de38bc621fbb0e783517bc",
                                 "profileName": "Malware Scan"}, {"profileId": "b9e01ede-c502-a064-cbca-e0f75d7743549709aaa0d800a65e","profileName": "DROWN Detection"}]
                  scannerList: [{"scannerId": 133708, "scannerName": "India Cloud Scanners"}, {"scannerId": 125641, "scannerName": "UK London Cloud Scanners"}]
                  scanType: 'tenable'
                  timestamp: 1590881696000
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  resceived:
                    type: string
                    description: Confirmation from cloud side.
              examples:
                value: {
                  received: 'yes'
                }
        '4XX':
          description: Client Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Bad Request:
                  $ref: '#/components/examples/BadRequestResponseExample'
                Unauthrorized Request:
                  $ref: '#/components/examples/UnauthorizedResponseExample'
          '5XX':
            description: Server Error Response
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorResponse'
                examples:
                  resolveSecurityAlertResponseExample:
                    $ref: '#/components/examples/ServerErrorResponseExample'


components:
  securitySchemes:
    $ref: 'components/securitySchemes.yaml#/securitySchemes'